swagger: "2.0"
info:
  title: Firebase Auth API Gateway
  description: Routes API Gateway to Cloud Function for Authentication
  version: "1.0.0"

paths:
  /auth:
    get:
      operationId: checkAuth
      x-google-backend:
        address: https://auth-bbcjdwvlwq-uc.a.run.app
      responses:
        200:
          description: Authentication response
          schema:
            type: object
            properties:
              authorized:
                type: boolean
        500:
          description: Internal Server Error
