version: '3.7'

services:
  fyc_boilerplate_backend_postgres_dev:
    container_name: fyc_boilerplate_backend_postgres_dev
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fyc
    ports:
      - 5432:5432
    restart: always
    networks:
      - fyc_boilerplate_backend_network_dev

  fyc_boilerplate_backend_redis_dev:
    container_name: fyc_boilerplate_backend_redis_dev
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    networks:
      - fyc_boilerplate_backend_network_dev

  fyc_boilerplate_backend_gateway_dev:
    container_name: fyc_boilerplate_backend_gateway_dev
    image: fyc_boilerplate_backend_gateway_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      # General
      - APP_URL=http://localhost:3333
      - APP_PORT=3333
      - NODE_ENV=development
      - DEFAULT_LANGUAGE=en
      - TZ=UTC
      # Cors
      - CORS_ALLOWED_FROM=*
      # Database
      - DATABASE_URL=postgresql://postgres:docker@fyc_boilerplate_backend_postgres_dev:5432/fyc?schema=public
      - DATABASE_LOGGER_ENABLED=false
      # Redis
      - REDIS_HOST=fyc_boilerplate_backend_redis_dev
      - REDIS_PORT=6379
      - REDIS_USER=
      - REDIS_PASS=
      - REDIS_DB=0
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    ports:
      - 3333:3333
    command: ./wait-for.sh fyc_boilerplate_backend_postgres_dev:5432 -s -- ./wait-for.sh fyc_boilerplate_backend_redis_dev:6379 -s -- bash -c "npx prisma migrate dev && npm run dev"
    depends_on:
      - fyc_boilerplate_backend_postgres_dev
      - fyc_boilerplate_backend_redis_dev
    restart: always
    networks:
      - fyc_boilerplate_backend_network_dev

networks:
  fyc_boilerplate_backend_network_dev:
