version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projectdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/pgData

  server:
    build:
      context: .
    container_name: server-container
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres-local:5432/projectdb?schema=public
      APP_PORT: 3001
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  volumes:
    pgData:
