name: Build and Deploy to GCP Cloud Run

on:
  push:
    branches: [ main, qa ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Set service name branch name
      run: echo "SERVICE_NAME=api-${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    - name: Build
      run: docker build -f Dockerfile.prod -t $REGION-docker.pkg.dev/$PROJECT_ID/api/$SERVICE_NAME:latest .

    - name: Push
      run: docker push $REGION-docker.pkg.dev/$PROJECT_ID/api/$SERVICE_NAME:latest

    - name: Deploy
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/api/$SERVICE_NAME:latest \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --ingress internal \
          --network default \
          --subnet default
